/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuraOneRouteImport } from './routes/aura-one'
import { Route as ConstructionLandingRouteImport } from './routes/construction-landing'
import { Route as KineticLabRouteImport } from './routes/kinetic-lab'
import { Route as MonolithArchitekturRouteImport } from './routes/monolith-architektur'
import { Route as SteelBladeRouteImport } from './routes/steel-blade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraOneRoute = AuraOneRouteImport.update({
  id: '/aura-one',
  path: '/aura-one',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionLandingRoute = ConstructionLandingRouteImport.update({
  id: '/construction-landing',
  path: '/construction-landing',
  getParentRoute: () => rootRouteImport,
} as any)
const KineticLabRoute = KineticLabRouteImport.update({
  id: '/kinetic-lab',
  path: '/kinetic-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const MonolithArchitekturRoute = MonolithArchitekturRouteImport.update({
  id: '/monolith-architektur',
  path: '/monolith-architektur',
  getParentRoute: () => rootRouteImport,
} as any)
const SteelBladeRoute = SteelBladeRouteImport.update({
  id: '/steel-blade',
  path: '/steel-blade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aura-one': typeof AuraOneRoute
  '/construction-landing': typeof ConstructionLandingRoute
  '/kinetic-lab': typeof KineticLabRoute
  '/monolith-architektur': typeof MonolithArchitekturRoute
  '/steel-blade': typeof SteelBladeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aura-one': typeof AuraOneRoute
  '/construction-landing': typeof ConstructionLandingRoute
  '/kinetic-lab': typeof KineticLabRoute
  '/monolith-architektur': typeof MonolithArchitekturRoute
  '/steel-blade': typeof SteelBladeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aura-one': typeof AuraOneRoute
  '/construction-landing': typeof ConstructionLandingRoute
  '/kinetic-lab': typeof KineticLabRoute
  '/monolith-architektur': typeof MonolithArchitekturRoute
  '/steel-blade': typeof SteelBladeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aura-one'
    | '/construction-landing'
    | '/kinetic-lab'
    | '/monolith-architektur'
    | '/steel-blade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aura-one'
    | '/construction-landing'
    | '/kinetic-lab'
    | '/monolith-architektur'
    | '/steel-blade'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aura-one'
    | '/construction-landing'
    | '/kinetic-lab'
    | '/monolith-architektur'
    | '/steel-blade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuraOneRoute: typeof AuraOneRoute
  ConstructionLandingRoute: typeof ConstructionLandingRoute
  KineticLabRoute: typeof KineticLabRoute
  MonolithArchitekturRoute: typeof MonolithArchitekturRoute
  SteelBladeRoute: typeof SteelBladeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura-one': {
      id: '/aura-one'
      path: '/aura-one'
      fullPath: '/aura-one'
      preLoaderRoute: typeof AuraOneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction-landing': {
      id: '/construction-landing'
      path: '/construction-landing'
      fullPath: '/construction-landing'
      preLoaderRoute: typeof ConstructionLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kinetic-lab': {
      id: '/kinetic-lab'
      path: '/kinetic-lab'
      fullPath: '/kinetic-lab'
      preLoaderRoute: typeof KineticLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monolith-architektur': {
      id: '/monolith-architektur'
      path: '/monolith-architektur'
      fullPath: '/monolith-architektur'
      preLoaderRoute: typeof MonolithArchitekturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steel-blade': {
      id: '/steel-blade'
      path: '/steel-blade'
      fullPath: '/steel-blade'
      preLoaderRoute: typeof SteelBladeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuraOneRoute: AuraOneRoute,
  ConstructionLandingRoute: ConstructionLandingRoute,
  KineticLabRoute: KineticLabRoute,
  MonolithArchitekturRoute: MonolithArchitekturRoute,
  SteelBladeRoute: SteelBladeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
